### ISSUE TITLE
баг - дебаг

### ISSUE THREAD

**Issue by EmperorDune** [DrMefistO/Gens-r57shell-Mod-Plus#1]
Если frameskip выставить на 8, и запустить дебагер и жать по step into или step over - постоянно срабатывает VBLANK, чуть ли не через каждые 10-20 инструкций.

gens_r57shell_mod от 4 мая 2014 г. - баг есть.
gens_r57shell_mod от 12 февраля 2013 г. - бага нет.

**Comment by DrMefistO** [comment]
Проверь текущий залитый в папке Output файлик. И скажи, есть ли бага.
